services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
